from .config import CfgNode as CN


_C = CN()

_C.MAX_EPOCH = 50
_C.DATE = ''
# dataset
_C.DATASET = CN()
_C.DATASET.NUM_CLASSES = 7
_C.DATASET.TRAIN_PATH = ['/data/zhangziwei/datasets/CelebA-HQ-img']
_C.DATASET.TEST_PATH = ['/data/zhangziwei/datasets/helen_star']
_C.DATASET.CLASSFUNC = 'FaskMask'
_C.DATASET.POSTPROCESS = CN()
_C.DATASET.POSTPROCESS.gray_scale = False
_C.DATASET.POSTPROCESS.edge_map = False
_C.DATASET.POSTPROCESS.four_channel = False

# model
_C.MODEL = CN()
_C.MODEL.DEVICE = 'cuda'
_C.MODEL.WEIGHTS = ''
_C.MODEL.PRETRAINED = 'imagenet'
_C.MODEL.TEACHER_NET = ''

# encoder
_C.MODEL.ENCODER = CN()
_C.MODEL.ENCODER.NAME = 'timm-mobilenetv3_large_minimal_100'
_C.MODEL.ENCODER.OUTPUT_STRIDE = 16

# FPN512
_C.MODEL.FPN = CN()
_C.MODEL.FPN.NAME = 'BIFPN'
_C.MODEL.FPN.OUT_CHANNELS = 88
_C.MODEL.FPN.PANET = False
_C.MODEL.FPN.NORM = None
_C.MODEL.FPN.STACK = 3

# DECODER
_C.MODEL.DECODER = CN()
_C.MODEL.DECODER.NAME = 'DeepLabV3Plus'
_C.MODEL.DECODER.CHANNELS = (256,)
_C.MODEL.DECODER.ASTROUS_RATES = (3, 5, 7)
_C.MODEL.DECODER.AUX = None
_C.MODEL.DECODER.SPP = 'ASPP'

# POSTPROCESS
_C.MODEL.POSTPROCESS = CN()
_C.MODEL.POSTPROCESS.NAME = ['SCSE', 'PointRend']
_C.MODEL.POSTPROCESS.FC_DIM = 256
_C.MODEL.POSTPROCESS.NUM_FC = 3
_C.MODEL.POSTPROCESS.REDUCTION = 4

# BLOCK
_C.MODEL.BLOCK = "BasicBlock"
# CONV2D
_C.MODEL.CONV2D = "Conv2d"

# INPUT
_C.INPUT = CN()
_C.INPUT.SIZE = (512, 512)
_C.INPUT.CROP = (448, 448)


_C.SOLVER = CN()
# OPTIMIZER
_C.SOLVER.OPTIMIZER = CN()
_C.SOLVER.OPTIMIZER.NAME = 'RAdam'
_C.SOLVER.OPTIMIZER.LR = 2e-3
_C.SOLVER.OPTIMIZER.WARMUP_LR = 1e-5

# LR_SCHEDULER
_C.SOLVER.LR_SCHEDULER = CN()
_C.SOLVER.LR_SCHEDULER.NAME = 'OneCycleLR'
_C.SOLVER.LR_SCHEDULER.MILESTONES = [10, 15]
_C.SOLVER.LR_SCHEDULER.T_MAX = 2000
_C.SOLVER.LR_SCHEDULER.MODE = ''
_C.SOLVER.LR_SCHEDULER.ACTOR = ''
_C.SOLVER.LR_SCHEDULER.PATIENCE = ''

_C.SOLVER.LOSS = 'DC_and_Focal_loss'
_C.SOLVER.GRADIENT_LOSS_WEIGHT = 0.5
_C.SOLVER.NUM_WORKERS = 16
_C.SOLVER.BATCH_SIZE = 64
_C.SOLVER.ACC_STEP = 1

_C.SOLVER.KD = CN()
_C.SOLVER.KD.ALPHA = 0.9
_C.SOLVER.KD.BETA = 0.1
_C.SOLVER.KD.TEMPERATURE = 10
_C.SOLVER.KD.MODE = ''

# OUTPUT
_C.OUTPUT_NAME = ''
_C.EXTRA = ''
_C.TASK = ''
